import { Organization } from './Organization';

export type ContactDetail = {
  readonly id: number;
  readonly org: Organization;
  readonly _deleteAfterDate?: string;
  readonly _deletedBy?: string;
  readonly _isCompany: boolean;
  readonly salutation: string;
  readonly firstName: string;
  readonly familyName: string;
  readonly name: string;
  readonly nameAffix: string;
  readonly dateOfBirth: string;
  readonly age: number;
  readonly professionalRole: string;
  readonly internalNote: string;
  readonly privateEmail: string;
  readonly companyEmail: string;
  readonly _preferredEmailField: number;
  readonly preferredCommunicationWay: number;
  readonly companyName: string;
  readonly invoiceCompany: boolean;
  readonly addressCompany: boolean;
  readonly privatePhone: string;
  readonly companyPhone: string;
  readonly mobilePhone: string;
  readonly street: string;
  readonly city: string;
  readonly state: string;
  readonly zip: string;
  readonly country: string;
  readonly companyStreet: string;
  readonly companyCity: string;
  readonly companyState: string;
  readonly companyZip: string;
  readonly companyCountry: string;
  readonly balance: string;
  readonly iban: string;
  readonly bic: string;
  readonly bankAccountOwner: string;
  readonly sepaMandate?: string;
  readonly sepaDate?: string;
  readonly methodOfPayment: number;
  readonly methodOfPaymentName: string;
  readonly referencedMemberPK: number;
  readonly datevAccountNumber: number;
  readonly copiedInstances: readonly unknown[];
  readonly groups: readonly unknown[];
  readonly customFields: readonly unknown[];
};
